CREATE TABLE TB_QUESTION_BANK_CATEGORY
(
	QUESTION_BANK_CATEGORY_ID	        VARCHAR2(100 BYTE)	NOT NULL
  , PARENT_QUESTION_BANK_CATEGORY_ID	VARCHAR2(100 BYTE)	NULL
  , QUESTION_BANK_CATEGORY_DEPTH	    NUMBER(3)	        NOT NULL
  , QUESTION_BANK_CATEGORY_SORT	        NUMBER(10)	        NULL
  , QUESTION_BANK_CATEGORY_TITLE	    VARCHAR2(200 BYTE)	NOT NULL
  , QUESTION_BANK_CATEGORY_DESCRIPTION	VARCHAR2(4000 BYTE)	NULL
  , REGISTRATION_DATE	                DATE	            NULL
  , REGISTER_ID	                        VARCHAR2(20 BYTE)	NULL
  , UPDATE_DATE	                        DATE	            NULL
  , UPDATE_USER_ID	                    VARCHAR2(20 BYTE)	NULL
  , CONSTRAINT  TB_QUESTION_BANK_CATEGORY_PK PRIMARY KEY (QUESTION_BANK_CATEGORY_ID)
);

COMMENT ON TABLE TB_QUESTION_BANK_CATEGORY IS '문제은행카테고리'; 
COMMENT ON COLUMN TB_QUESTION_BANK_CATEGORY.QUESTION_BANK_CATEGORY_ID IS '문제은행카테고리ID'; 
COMMENT ON COLUMN TB_QUESTION_BANK_CATEGORY.PARENT_QUESTION_BANK_CATEGORY_ID IS '부모문제은행카테고리ID'; 
COMMENT ON COLUMN TB_QUESTION_BANK_CATEGORY.QUESTION_BANK_CATEGORY_DEPTH IS '문제은행카테고리깊이'; 
COMMENT ON COLUMN TB_QUESTION_BANK_CATEGORY.QUESTION_BANK_CATEGORY_SORT IS '문제은행카테고리순서';
COMMENT ON COLUMN TB_QUESTION_BANK_CATEGORY.QUESTION_BANK_CATEGORY_TITLE IS '문제은행카테고리타이틀';
COMMENT ON COLUMN TB_QUESTION_BANK_CATEGORY.QUESTION_BANK_CATEGORY_DESCRIPTION IS '문제은행카테고리설명';
COMMENT ON COLUMN TB_QUESTION_BANK_CATEGORY.REGISTRATION_DATE IS '등록일시';
COMMENT ON COLUMN TB_QUESTION_BANK_CATEGORY.REGISTER_ID IS '등록자ID';
COMMENT ON COLUMN TB_QUESTION_BANK_CATEGORY.UPDATE_DATE IS '수정일시';
COMMENT ON COLUMN TB_QUESTION_BANK_CATEGORY.UPDATE_USER_ID IS '수정자ID';


CREATE TABLE TB_QUESTION_BANK_QESITM
(
	QUESTION_BANK_QESITM_ID	         VARCHAR2(100 BYTE)	    NOT NULL
  , QUESTION_BANK_QESITM_TITLE	     VARCHAR2(200 BYTE)	    NOT NULL
  , QUESTION_BANK_QESITM_CONTENTS	 VARCHAR2(4000 BYTE)	NULL
  , QUESTION_BANK_QESITM_EXPLANATION VARCHAR2(4000 BYTE)	NULL
  , QUESTION_BANK_QESITM_SCORE       NUMBER(5,2)	        NOT NULL
  , QUESTION_BANK_QESITM_TYPE_CODE   VARCHAR2(8 BYTE)       NOT NULL
  , REGISTRATION_DATE	             DATE	                NULL
  , REGISTER_ID	                     VARCHAR2(20 BYTE)	    NULL
  , UPDATE_DATE	                     DATE	                NULL
  , UPDATE_USER_ID	                 VARCHAR2(20 BYTE)	    NULL
  , CONSTRAINT  TB_QUESTION_BANK_QESITM_PK PRIMARY KEY (QUESTION_BANK_QESITM_ID)
);

COMMENT ON TABLE TB_QUESTION_BANK_QESITM IS '문제은행문항'; 
COMMENT ON COLUMN TB_QUESTION_BANK_QESITM.QUESTION_BANK_QESITM_ID IS '문제은행문항ID'; 
COMMENT ON COLUMN TB_QUESTION_BANK_QESITM.QUESTION_BANK_QESITM_TITLE IS '문제은행문항타이틀'; 
COMMENT ON COLUMN TB_QUESTION_BANK_QESITM.QUESTION_BANK_QESITM_CONTENTS IS '문제은행문항내용'; 
COMMENT ON COLUMN TB_QUESTION_BANK_QESITM.QUESTION_BANK_QESITM_EXPLANATION IS '문제은행문항해설';
COMMENT ON COLUMN TB_QUESTION_BANK_QESITM.QUESTION_BANK_QESITM_SCORE IS '문제은행문항점수';
COMMENT ON COLUMN TB_QUESTION_BANK_QESITM.QUESTION_BANK_QESITM_TYPE_CODE IS '문제은행문항타입코드';
COMMENT ON COLUMN TB_QUESTION_BANK_QESITM.REGISTRATION_DATE IS '등록일시';
COMMENT ON COLUMN TB_QUESTION_BANK_QESITM.REGISTER_ID IS '등록자ID';
COMMENT ON COLUMN TB_QUESTION_BANK_QESITM.UPDATE_DATE IS '수정일시';
COMMENT ON COLUMN TB_QUESTION_BANK_QESITM.UPDATE_USER_ID IS '수정자ID';








CREATE TABLE TB_QUESTION_BANK_QESITM_ITEM
(
    QUESTION_BANK_QESITM_ITEM_ID	  VARCHAR2(100 BYTE)	NOT NULL
  , QUESTION_BANK_QESITM_ID	          VARCHAR2(100 BYTE)	NOT NULL
  , QUESTION_BANK_QESITM_ITEM_SORT	  VARCHAR2(4000 BYTE)	NULL
  , QUESTION_BANK_QESITM_ITEM_TITLE	  VARCHAR2(200 BYTE)	NULL
  , QUESTION_BANK_QESITM_ITEM_CNSR_YN VARCHAR2(1 BYTE)	    NOT NULL
  , QUESTION_BANK_QESITM_ITEM_CNSR_CONTENTS	  VARCHAR2(4000 BYTE)	NULL
  , REGISTRATION_DATE	                      DATE	                NULL
  , REGISTER_ID	                              VARCHAR2(20 BYTE)	    NULL
  , UPDATE_DATE	                              DATE	                NULL
  , UPDATE_USER_ID	                          VARCHAR2(20 BYTE)	    NULL
  , CONSTRAINT  TB_QUESTION_BANK_QESITM_ITEM_PK PRIMARY KEY (QUESTION_BANK_QESITM_ITEM_ID)
  , CONSTRAINT  TB_QUESTION_BANK_QESITM_ITEM_FK1 FOREIGN KEY (QUESTION_BANK_QESITM_ID) REFERENCES TB_QUESTION_BANK_QESITM(QUESTION_BANK_QESITM_ID)
);

COMMENT ON TABLE TB_QUESTION_BANK_QESITM_ITEM IS '문제은행문항아이템'; 
COMMENT ON COLUMN TB_QUESTION_BANK_QESITM_ITEM.QUESTION_BANK_QESITM_ITEM_ID IS '문제은행문항아이템ID'; 
COMMENT ON COLUMN TB_QUESTION_BANK_QESITM_ITEM.QUESTION_BANK_QESITM_ID IS '문제은행문항ID'; 
COMMENT ON COLUMN TB_QUESTION_BANK_QESITM_ITEM.QUESTION_BANK_QESITM_ITEM_SORT IS '문제은행문항아이템순번'; 
COMMENT ON COLUMN TB_QUESTION_BANK_QESITM_ITEM.QUESTION_BANK_QESITM_ITEM_TITLE IS '문제은행문항아이템타이틀';
COMMENT ON COLUMN TB_QUESTION_BANK_QESITM_ITEM.QUESTION_BANK_QESITM_ITEM_CNSR_YN IS '문제은행문항아이템정답여부';
COMMENT ON COLUMN TB_QUESTION_BANK_QESITM_ITEM.QUESTION_BANK_QESITM_ITEM_CNSR_CONTENTS IS '문제은행문항아이템정답내용';
COMMENT ON COLUMN TB_QUESTION_BANK_QESITM_ITEM.REGISTRATION_DATE IS '등록일시';
COMMENT ON COLUMN TB_QUESTION_BANK_QESITM_ITEM.REGISTER_ID IS '등록자ID';
COMMENT ON COLUMN TB_QUESTION_BANK_QESITM_ITEM.UPDATE_DATE IS '수정일시';
COMMENT ON COLUMN TB_QUESTION_BANK_QESITM_ITEM.UPDATE_USER_ID IS '수정자ID';



CREATE TABLE TB_QUESTION_BANK_EXAM_MASTER
(
    QUESTION_BANK_EXAM_ID	          VARCHAR2(100 BYTE)	NOT NULL
  , QUESTION_BANK_EXAM_TITLE	      VARCHAR2(200 BYTE)	NOT NULL
  , REGISTRATION_DATE	              DATE	                NULL
  , REGISTER_ID	                      VARCHAR2(20 BYTE)	    NULL
  , UPDATE_DATE	                      DATE	                NULL
  , UPDATE_USER_ID	                  VARCHAR2(20 BYTE)	    NULL
  , CONSTRAINT  TB_QUESTION_BANK_EXAM_MASTER_PK PRIMARY KEY (QUESTION_BANK_EXAM_ID)
);

COMMENT ON TABLE TB_QUESTION_BANK_EXAM_MASTER IS '문제은행시험마스터'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_MASTER.QUESTION_BANK_EXAM_ID IS '문제은행시험ID'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_MASTER.QUESTION_BANK_EXAM_TITLE IS '문제은행시험타이틀'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_MASTER.REGISTRATION_DATE IS '등록일시';
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_MASTER.REGISTER_ID IS '등록자ID';
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_MASTER.UPDATE_DATE IS '수정일시';
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_MASTER.UPDATE_USER_ID IS '수정자ID';





CREATE TABLE TB_QUESTION_BANK_EXAM_QESITM
(
    QUESTION_BANK_EXAM_QESITM_ID	        VARCHAR2(100 BYTE)	NOT NULL
  , QUESTION_BANK_EXAM_ID	                VARCHAR2(100 BYTE)	NOT NULL
  , QUESTION_BANK_EXAM_QESITM_SORT	        NUMBER(10)	        NOT NULL
  , QUESTION_BANK_EXAM_QESITM_TITLE	        VARCHAR2(200 BYTE)	NOT NULL
  , QUESTION_BANK_EXAM_QESITM_CONTENTS	    VARCHAR2(4000 BYTE)	NULL
  , QUESTION_BANK_EXAM_QESITM_DESCRIPTION	VARCHAR2(4000 BYTE)	NULL
  , QUESTION_BANK_EXAM_QESITM_SCORE	        NUMBER(5,2)	        NOT NULL
  , REGISTRATION_DATE	                    DATE	            NULL
  , REGISTER_ID	                            VARCHAR2(20 BYTE)	NULL
  , UPDATE_DATE	                            DATE	            NULL
  , UPDATE_USER_ID	                        VARCHAR2(20 BYTE)	NULL

  , CONSTRAINT  TB_QUESTION_BANK_EXAM_QESITM_PK PRIMARY KEY (QUESTION_BANK_EXAM_QESITM_ID)
  , CONSTRAINT  TB_QUESTION_BANK_EXAM_QESITM_FK1 FOREIGN KEY (QUESTION_BANK_EXAM_ID) REFERENCES TB_QUESTION_BANK_EXAM_MASTER(QUESTION_BANK_EXAM_ID)
);

COMMENT ON TABLE TB_QUESTION_BANK_EXAM_QESITM IS '문제은행시험문항'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_QESITM.QUESTION_BANK_EXAM_QESITM_ID IS '문제은행시험문항ID'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_QESITM.QUESTION_BANK_EXAM_ID IS '문제은행시험ID'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_QESITM.QUESTION_BANK_EXAM_QESITM_SORT IS '문제은행시험문항순서'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_QESITM.QUESTION_BANK_EXAM_QESITM_TITLE IS '문제은행시험문항타이틀'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_QESITM.QUESTION_BANK_EXAM_QESITM_CONTENTS IS '문제은행시험문항내용'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_QESITM.QUESTION_BANK_EXAM_QESITM_DESCRIPTION IS '문제은행시험문항설명'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_QESITM.QUESTION_BANK_EXAM_QESITM_SCORE IS '문제은행시험문항점수'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_QESITM.REGISTRATION_DATE IS '등록일시';
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_QESITM.REGISTER_ID IS '등록자ID';
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_QESITM.UPDATE_DATE IS '수정일시';
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_QESITM.UPDATE_USER_ID IS '수정자ID';



CREATE TABLE TB_QUESTION_BANK_EXAM_QESITM_ITEM
(
    QUESTION_BANK_EXAM_QESITM_ITEM_ID	    VARCHAR2(100 BYTE)	NOT NULL
  , QUESTION_BANK_EXAM_QESITM_ID	        VARCHAR2(100 BYTE)	NOT NULL
  , QUESTION_BANK_EXAM_QESITM_ITEM_SORT	    NUMBER(10)	        NOT NULL
  , QUESTION_BANK_EXAM_QESITM_ITEM_TITLE	VARCHAR2(200 BYTE)	NOT NULL
  , QUESTION_BANK_EXAM_QESITM_ITEM_CNSR_YN	VARCHAR2(1 BYTE)	NOT NULL
  , REGISTRATION_DATE	                    DATE	            NULL
  , REGISTER_ID	                            VARCHAR2(20 BYTE)	NULL
  , UPDATE_DATE	                            DATE	            NULL
  , UPDATE_USER_ID	                        VARCHAR2(20 BYTE)	NULL


  , CONSTRAINT  TB_QUESTION_BANK_EXAM_QESITM_ITEM_PK PRIMARY KEY (QUESTION_BANK_EXAM_QESITM_ITEM_ID)
  , CONSTRAINT  TB_QUESTION_BANK_EXAM_QESITM_ITEM_FK1 FOREIGN KEY (QUESTION_BANK_EXAM_QESITM_ID) REFERENCES TB_QUESTION_BANK_EXAM_QESITM(QUESTION_BANK_EXAM_QESITM_ID)
);

COMMENT ON TABLE TB_QUESTION_BANK_EXAM_QESITM_ITEM IS '문제은행시험문항아이템'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_QESITM_ITEM.QUESTION_BANK_EXAM_QESITM_ITEM_ID IS '문제은행시험문항아이템ID'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_QESITM_ITEM.QUESTION_BANK_EXAM_QESITM_ID IS '문제은행시험문항ID'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_QESITM_ITEM.QUESTION_BANK_EXAM_QESITM_ITEM_SORT IS '문제은행시험문항아이템순서'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_QESITM_ITEM.QUESTION_BANK_EXAM_QESITM_ITEM_TITLE IS '문제은행시험문항아이템타이틀'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_QESITM_ITEM.QUESTION_BANK_EXAM_QESITM_ITEM_CNSR_YN IS '문제은행시험문항아이템정답여부'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_QESITM_ITEM.REGISTRATION_DATE IS '등록일시';
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_QESITM_ITEM.REGISTER_ID IS '등록자ID';
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_QESITM_ITEM.UPDATE_DATE IS '수정일시';
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_QESITM_ITEM.UPDATE_USER_ID IS '수정자ID';






CREATE TABLE TB_QUESTION_BANK_EXAM_APYEXM
( 
    QUESTION_BANK_EXAM_ID	            VARCHAR2(100 BYTE)	NOT NULL
  , QUESTION_BANK_EXAM_APYEXM_ORDER	    NUMBER(3)	        NOT NULL
  , QUESTION_BANK_EXAM_EXAMINEE_ID	    VARCHAR2(20 BYTE)	NOT NULL
  , QUESTION_BANK_EXAM_GRADING_SCORE	NUMBER(5,2)	        NULL
  , QUESTION_BANK_EXAM_START_DATE	    DATE	            NULL
  , QUESTION_BANK_EXAM_END_DATE	        DATE	            NULL
  , REGISTRATION_DATE	                DATE	            NULL
  , REGISTER_ID	                        VARCHAR2(20 BYTE)	NULL
  , UPDATE_DATE	                        DATE	            NULL
  , UPDATE_USER_ID	                    VARCHAR2(20 BYTE)	NULL



  , CONSTRAINT  TB_QUESTION_BANK_EXAM_APYEXM_PK PRIMARY KEY (QUESTION_BANK_EXAM_ID , QUESTION_BANK_EXAM_APYEXM_ORDER, QUESTION_BANK_EXAM_EXAMINEE_ID)
  , CONSTRAINT  TB_QUESTION_BANK_EXAM_APYEXM_FK1 FOREIGN KEY (QUESTION_BANK_EXAM_ID) REFERENCES TB_QUESTION_BANK_EXAM_MASTER(QUESTION_BANK_EXAM_ID)
);

COMMENT ON TABLE TB_QUESTION_BANK_EXAM_APYEXM IS '문제은행시험응시'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_APYEXM.QUESTION_BANK_EXAM_ID IS '문제은행시험ID'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_APYEXM.QUESTION_BANK_EXAM_APYEXM_ORDER IS '문제은행시험응시차수'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_APYEXM.QUESTION_BANK_EXAM_EXAMINEE_ID IS '문제은행시험응시자ID'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_APYEXM.QUESTION_BANK_EXAM_GRADING_SCORE IS '문제은행시험채점점수'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_APYEXM.QUESTION_BANK_EXAM_START_DATE IS '문제은행시험시작시간'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_APYEXM.QUESTION_BANK_EXAM_END_DATE IS '문제은행시험종료시간'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_APYEXM.REGISTRATION_DATE IS '등록일시';
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_APYEXM.REGISTER_ID IS '등록자ID';
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_APYEXM.UPDATE_DATE IS '수정일시';
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_APYEXM.UPDATE_USER_ID IS '수정자ID';



CREATE TABLE TB_QUESTION_BANK_EXAM_ASWPER
( 
    QUESTION_BANK_EXAM_ASWPER_ID	    VARCHAR2(100 BYTE)	NOT NULL
  , QUESTION_BANK_EXAM_ID	            VARCHAR2(100 BYTE)	NOT NULL
  , QUESTION_BANK_EXAM_APYEXM_ORDER	    NUMBER(3)	        NOT NULL
  , QUESTION_BANK_EXAM_EXAMINEE_ID	    VARCHAR2(20 BYTE)	NOT NULL
  , QUESTION_BANK_EXAM_QESITM_ID	    VARCHAR2(100 BYTE)	NOT NULL
  , QUESTION_BANK_EXAM_QESITM_ITEM_ID	VARCHAR2(100 BYTE)	NULL
  , REGISTRATION_DATE	                DATE	            NULL
  , REGISTER_ID	                        VARCHAR2(20 BYTE)	NULL
  , UPDATE_DATE	                        DATE	            NULL
  , UPDATE_USER_ID	                    VARCHAR2(20 BYTE)	NULL




  , CONSTRAINT  TB_QUESTION_BANK_EXAM_ASWPER_PK PRIMARY KEY (QUESTION_BANK_EXAM_ASWPER_ID)
  , CONSTRAINT  TB_QUESTION_BANK_EXAM_ASWPER_FK1 FOREIGN KEY (QUESTION_BANK_EXAM_ID,QUESTION_BANK_EXAM_APYEXM_ORDER,QUESTION_BANK_EXAM_EXAMINEE_ID) REFERENCES TB_QUESTION_BANK_EXAM_APYEXM(QUESTION_BANK_EXAM_ID,QUESTION_BANK_EXAM_APYEXM_ORDER,QUESTION_BANK_EXAM_EXAMINEE_ID)
);

COMMENT ON TABLE TB_QUESTION_BANK_EXAM_ASWPER IS '문제은행시험응시'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_ASWPER.QUESTION_BANK_EXAM_ID IS '문제은행시험ID'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_ASWPER.QUESTION_BANK_EXAM_APYEXM_ORDER IS '문제은행시험응시차수'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_ASWPER.QUESTION_BANK_EXAM_EXAMINEE_ID IS '문제은행시험응시자ID'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_ASWPER.QUESTION_BANK_EXAM_GRADING_SCORE IS '문제은행시험채점점수'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_ASWPER.QUESTION_BANK_EXAM_START_DATE IS '문제은행시험시작시간'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_ASWPER.QUESTION_BANK_EXAM_END_DATE IS '문제은행시험종료시간'; 
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_ASWPER.REGISTRATION_DATE IS '등록일시';
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_ASWPER.REGISTER_ID IS '등록자ID';
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_ASWPER.UPDATE_DATE IS '수정일시';
COMMENT ON COLUMN TB_QUESTION_BANK_EXAM_ASWPER.UPDATE_USER_ID IS '수정자ID';




